---
- name: Set DNS Address
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - 127.0.0.1
      - 8.8.8.8
    log_path: C:\dns_log.txt

# Install AD
- name: Create new AD domain
  win_domain:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ ansible_password }}"
  register: domain_install

- name: Reboot after AD installation
  win_reboot:
  when: domain_install.reboot_required

- name: Ensure xActiveDirectory PS DSC module is installed
  win_psmodule:
    name: xActiveDirectory
    state: present

- name: Wait for domain to be available
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ domain_name }}"
    RetryCount: 100
    RetryIntervalSec: 10
  when: packer is not defined  



  