- name: Configure DNS settings
  win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - 10.0.0.9
      log_path: C:\dns_log.txt

- name: Join machine to domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ ansible_user }}@{{ domain_name }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state

- name: Reboot after joining domain
  win_reboot:
  when: domain_state.reboot_required

- name: Disable Domain firewall
  community.windows.win_firewall:
    state: disabled
    profiles:
    - Domain
  tags: disable_firewall

- name: Add a domain user to a local admin group
  ansible.windows.win_group_membership:
    name: Administrators
    members:
      - aurora\Adam      
    state: present

- name: install packages
  chocolatey.chocolatey.win_chocolatey:
     name: "googlechrome"
     state: present
     ignore_checksums: true